# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 889154e3f9e7b15baed980f6fd873fd5e846899ea6394a892c01016e571aeb01e3003fc9aec8e04002061bc84e93b382973d0f4ef77f1128222f6adf2f1929a5

test:
  secret_key_base: caad6173fe04894c2f43eaddc4b49d4bb9a7c3807b27b7c7158bd0ef0989ab92f5d94da1614acbe84a4a36adf9f162e982b44c3edd68331136ef79d543d45a93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
